# Generated by Django 5.1.2 on 2024-10-31 16:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.localtime, editable=False),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='is_deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
