# Generated by Django 6.0.8 on 2026-08-09 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('sub_domain_description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Domain',
                'verbose_name_plural': 'Domains',
                'db_table': 'django_spire_metric_domain',
            },
        ),
        migrations.CreateModel(
            name='StatisticGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_groups', related_query_name='statistic_group', to='django_spire_metric_domain.domain')),
            ],
            options={
                'verbose_name': 'Statistic Group',
                'verbose_name_plural': 'Statistics Group',
                'db_table': 'django_spire_metric_domain_statistic_group',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('interval', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', related_query_name='statistic', to='django_spire_metric_domain.statisticgroup')),
            ],
            options={
                'verbose_name': 'Statistic',
                'verbose_name_plural': 'Statistics',
                'db_table': 'django_spire_metric_domain_statistic',
            },
        ),
        migrations.CreateModel(
            name='SubDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdomains', related_query_name='subdomain', to='django_spire_metric_domain.domain')),
            ],
            options={
                'verbose_name': 'Sub Domain',
                'verbose_name_plural': 'Sub Domains',
                'db_table': 'django_spire_metric_sub_domain',
            },
        ),
        migrations.CreateModel(
            name='StatisticValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', related_query_name='value', to='django_spire_metric_domain.statistic')),
            ],
            options={
                'verbose_name': 'Statistic Value',
                'verbose_name_plural': 'Statistic Values',
                'db_table': 'django_spire_metric_domain_statistic_value',
                'constraints': [models.UniqueConstraint(fields=('statistic', 'reference', 'date'), name='unique_statistic_value_reference_date')],
            },
        ),
    ]
