# Generated by Django 6.0.6 on 2026-07-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_domain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='key',
        ),
        migrations.AddField(
            model_name='domain',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='domain',
            name='sub_domain_description',
            field=models.TextField(default=''),
        ),
    ]
