# Generated by Django 6.0.6 on 2026-07-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metric_domain', '0002_remove_domain_key_domain_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdomain',
            options={'verbose_name': 'Sub Domain', 'verbose_name_plural': 'Sub Domains'},
        ),
    ]
