# Generated by Django 6.0.8 on 2026-08-24 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0003_subdomain_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
