# Generated by Django 6.0.8 on 2026-08-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0004_alter_statistic_key_alter_subdomain_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='value_type',
            field=models.CharField(blank=True, choices=[('currency', 'Currency'), ('percentage', 'Percentage'), ('number', 'Number')], default='number', max_length=20),
        ),
    ]
