# Generated by Django 6.0.8 on 2026-08-06 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_domain', '0004_statisticgroup_statistic_statisticvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', related_query_name='statistic', to='metric_domain.statisticgroup'),
        ),
    ]
