# Generated by Django 6.0.8 on 2026-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0005_statistic_value_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statisticgroup',
            options={'verbose_name': 'Statistic Group', 'verbose_name_plural': 'Statistics Groups'},
        ),
        migrations.RenameField(
            model_name='domain',
            old_name='sub_domain_description',
            new_name='sub_domain_name',
        ),
    ]
