# Generated by Django 6.0.8 on 2026-08-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0006_alter_statisticgroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='sub_domain_name',
            field=models.CharField(max_length=128),
        ),
    ]
