# Generated by Django 6.0.8 on 2026-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0007_alter_domain_sub_domain_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='statisticvalue',
            index=models.Index(fields=['statistic', 'reference', 'timestamp'], name='ix_statistic_reference_ts'),
        ),
    ]
