# Generated by Django 6.0.8 on 2026-08-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_domain', '0008_statisticvalue_ix_statistic_reference_ts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='key',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='subdomain',
            name='key',
            field=models.SlugField(blank=True, max_length=64, unique=True),
        ),
    ]
