# Generated by Django 5.2.5 on 2025-09-02 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('order', models.PositiveIntegerField(default=0, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#ff0000', max_length=7)),
            ],
            options={
                'verbose_name': 'Ordering',
                'verbose_name_plural': 'Orderings',
                'db_table': 'apps_ordering',
            },
        ),
    ]
