# Generated by Django 6.0.6 on 2026-07-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_ordering', '0002_alter_duck_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duck',
            options={'verbose_name': 'Duck', 'verbose_name_plural': 'Ducks'},
        ),
    ]
