# Generated by Django 5.2.5 on 2025-09-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entry',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entryversionblock',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entryversionblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('sub_heading', 'Sub Heading'), ('list_item', 'List Item')], default='text', max_length=32),
        ),
    ]
