# Generated by Django 5.2.6 on 2025-09-23 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_auth_group', '0001_initial'),
        ('django_spire_knowledge', '0003_alter_collection_order_alter_entry_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('can_change_globally', 'Can Change Globally'), ('can_change_collection_groups', 'Can Change Collection Groups')], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.CreateModel(
            name='CollectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_groups', related_query_name='collection_group', to='django_spire_auth_group.authgroup')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='group', to='django_spire_knowledge.collection')),
            ],
        ),
    ]
