# Generated by Django 5.2.7 on 2025-10-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_knowledge', '0004_alter_collection_options_collectiongroup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'permissions': [('can_access_all_collections', 'Can Access All Collections'), ('can_change_collection_groups', 'Can Change Collection Groups'), ('can_reorder', 'Can Reorder Collections')], 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
    ]
