# Generated by Django 5.2.7 on 2025-11-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_core', '0001_initial'),
        ('django_spire_knowledge', '0007_alter_collection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='aggregated_tags',
            field=models.ManyToManyField(related_name='+', to='django_spire_core.tag'),
        ),
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='django_spire_core.tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='aggregated_tags',
            field=models.ManyToManyField(related_name='+', to='django_spire_core.tag'),
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(related_name='+', to='django_spire_core.tag'),
        ),
    ]
