# Generated by Django 5.2.8 on 2026-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_core', '0001_initial'),
        ('django_spire_knowledge', '0008_collection_tags_entry_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='tags',
            field=models.ManyToManyField(blank=True, editable=False, related_name='+', to='django_spire_core.tag'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(blank=True, editable=False, related_name='+', to='django_spire_core.tag'),
        ),
    ]
