# Generated by Django 6.0.8 on 2026-08-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_knowledge', '0010_entry__search_text_entry__search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryversionblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('heading', 'Heading'), ('list', 'List'), ('code', 'Code')], default='text', max_length=32),
        ),
    ]
