# Generated by Django 5.1.15 on 2026-01-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_knowledge', '0010_entry__search_text_entry__search_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entryversionblock',
            name='type',
            field=models.CharField(choices=[('code', 'Code'), ('heading', 'Heading'), ('list', 'List'), ('text', 'Text')], default='text', max_length=32),
        ),
    ]
