# Generated by Django 5.2.1 on 2025-05-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='appnotification',
            name='context_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='appnotification',
            name='template',
            field=models.TextField(default='django_spire/notification/app/item/notification_item.html'),
        ),
    ]
