# Generated by Django 5.2.11 on 2026-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnotification',
            name='template',
            field=models.TextField(default='django_spire/notification/app/item/list_item.html'),
        ),
    ]
