# Generated by Django 5.2.2 on 2025-06-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification_sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotification',
            name='media_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
