# Generated by Django 5.2.5 on 2025-09-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duck',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
