# Generated by Django 5.1.6 on 2025-03-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire_history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysubscriber',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitysubscriber',
            name='subscriber',
        ),
        migrations.RemoveField(
            model_name='view',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='ActivitySubscriber',
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
