# Generated by Django 5.1.8 on 2025-05-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification', '0002_pushnotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushNotification',
        ),
    ]
