# Generated by Django 5.2.13 on 2026-04-08 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestRestUser',
            new_name='Pirate',
        ),
        migrations.AlterModelOptions(
            name='pirate',
            options={'verbose_name': 'Pirate', 'verbose_name_plural': 'Pirates'},
        ),
    ]
