# Generated by Django 5.2.1 on 2025-05-12 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailnotification',
            name='subject',
        ),
    ]
