# Generated by Django 5.2.1 on 2025-05-13 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_notification', '0003_rename_processed_datetime_notification_sent_datetime_and_more'),
        ('django_spire_notification_email', '0002_remove_emailnotification_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailnotification',
            old_name='email',
            new_name='to_email_address',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='notification',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='email', related_query_name='email', to='django_spire_notification.notification'),
        ),
    ]
