# Generated by Django 5.2.7 on 2026-03-08 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=128)),
                ('hashed_key', models.CharField(editable=False, max_length=128)),
                ('key_hint', models.CharField(editable=False, max_length=16)),
            ],
            options={
                'verbose_name': 'API Access',
                'verbose_name_plural': 'API Accesses',
                'db_table': 'django_spire_api_access',
                'ordering': ('name',),
            },
        ),
    ]
