# Generated by Django 5.2.7 on 2026-03-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'View'), (2, 'Add'), (3, 'Change'), (4, 'Delete')], default=1),
        ),
    ]
