# Generated by Django 6.0.8 on 2026-09-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_api', '0002_apiaccess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccess',
            name='has_super_access',
            field=models.BooleanField(default=False),
        ),
    ]
