# Generated by Django 6.0.8 on 2026-09-03 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_api', '0003_apiaccess_has_super_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='has_super_access',
            field=models.BooleanField(default=False, verbose_name='Super Access (Overrides Base Permission & User Access)'),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Key Name'),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'View'), (2, 'Add'), (3, 'Change'), (4, 'Delete')], default=1, verbose_name='Base Permission'),
        ),
        migrations.AlterField(
            model_name='apiaccess',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_access', related_query_name='api_access', to=settings.AUTH_USER_MODEL, verbose_name='User Access'),
        ),
    ]
