# Generated by Django 6.0.6 on 2026-09-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_api', '0004_alter_apiaccess_has_super_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiaccess',
            name='has_super_access',
            field=models.BooleanField(default=False, verbose_name='Super Access (Overrides User Access)'),
        ),
    ]
