# Generated by Django 5.2.13 on 2026-04-25 04:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_field_timestamps', models.JSONField(default=dict, editable=False)),
                ('sync_field_last_modified', models.BigIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_name', models.CharField(default='', max_length=255)),
                ('contact_email', models.EmailField(default='', max_length=254)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_field_timestamps', models.JSONField(default=dict, editable=False)),
                ('sync_field_last_modified', models.BigIntegerField(db_index=True, default=0, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('region', models.CharField(default='', max_length=100)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('complete', 'Complete')], default='planning', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', related_query_name='site', to='test_project_sync.client')),
            ],
            options={
                'ordering': ['-sync_field_last_modified'],
            },
        ),
        migrations.CreateModel(
            name='SurveyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_field_timestamps', models.JSONField(default=dict, editable=False)),
                ('sync_field_last_modified', models.BigIntegerField(db_index=True, default=0, editable=False)),
                ('plan_number', models.CharField(default='', max_length=20)),
                ('stake_spacing_m', models.DecimalField(decimal_places=1, default=50, max_digits=6)),
                ('line_direction', models.CharField(choices=[('NS', 'North-South'), ('EW', 'East-West'), ('NE-SW', 'Northeast-Southwest'), ('NW-SE', 'Northwest-Southeast')], default='NS', max_length=5)),
                ('headland_offset_m', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('office_notes', models.TextField(default='')),
                ('baseline_a_latitude', models.FloatField(default=0)),
                ('baseline_a_longitude', models.FloatField(default=0)),
                ('baseline_b_latitude', models.FloatField(default=0)),
                ('baseline_b_longitude', models.FloatField(default=0)),
                ('heading_degrees', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('crew_notes', models.TextField(default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in-progress', 'In Progress'), ('reviewed', 'Reviewed')], default='draft', max_length=20)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', related_query_name='plan', to='test_project_sync.site')),
            ],
            options={
                'ordering': ['-sync_field_last_modified'],
            },
        ),
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_field_timestamps', models.JSONField(default=dict, editable=False)),
                ('sync_field_last_modified', models.BigIntegerField(db_index=True, default=0, editable=False)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('elevation', models.FloatField(default=0)),
                ('is_placed', models.BooleanField(default=False)),
                ('stake_type', models.CharField(choices=[('boundary', 'Boundary'), ('control', 'Control'), ('offset', 'Offset'), ('reference', 'Reference')], default='boundary', max_length=20)),
                ('label', models.CharField(default='', max_length=50)),
                ('survey_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakes', related_query_name='stake', to='test_project_sync.surveyplan')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
