# Generated by Django 5.2.14 on 2026-06-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project_sync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sync_field_origin_node',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_field_sequence',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='site',
            name='sync_field_origin_node',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='sync_field_sequence',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='stake',
            name='sync_field_origin_node',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='stake',
            name='sync_field_sequence',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='surveyplan',
            name='sync_field_origin_node',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='surveyplan',
            name='sync_field_sequence',
            field=models.BigIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
