# Generated by Django 5.1.2 on 2024-11-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire_authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MfaCode',
        ),
    ]
