# Generated by Django 5.1.2 on 2024-11-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mfacode',
            table='spire_authentication_mfa_code',
        ),
    ]
