# Generated by Django 5.2.13 on 2026-05-08 04:31

import django.utils.timezone
import django_spire.celery.models
import django_spire.celery.result
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(editable=False)),
                ('task_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('reference_key', models.CharField(max_length=128)),
                ('model_key', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(choices=django_spire.celery.models._celery_state_choices, default='PENDING', max_length=16)),
                ('_task_meta', models.JSONField(blank=True, default=dict, null=True)),
                ('started_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('_result', models.BinaryField(default=django_spire.celery.result.set_pickled_no_result)),
                ('_result_capture_attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Celery Task',
                'verbose_name_plural': 'Celery Tasks',
                'db_table': 'django_spire_celery_task',
                'ordering': ('-started_datetime',),
            },
        ),
    ]
