# Generated by Django 5.2.13 on 2026-04-13 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(editable=False)),
                ('reference_key', models.CharField(max_length=128)),
                ('app_name', models.CharField(max_length=128)),
                ('reference_name', models.CharField(max_length=128)),
                ('state', models.CharField(choices=[('REVOKED', 'REVOKED'), ('RECEIVED', 'RECEIVED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'), ('RETRY', 'RETRY'), ('PENDING', 'PENDING'), ('FAILURE', 'FAILURE')], default='PENDING', max_length=16)),
                ('started_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_datetime', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-started_datetime',),
            },
        ),
    ]
