# Generated by Django 5.2.14 on 2026-05-18 00:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_celery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='queued_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='celerytask',
            name='started_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
