# Generated by Django 5.2.13 on 2026-04-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_celery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='model_key',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
