# Generated by Django 6.0.6 on 2026-09-10 18:06

import django_spire.celery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_celery', '0003_rename__result_capture_attempts_celerytask_result_capture_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='state',
            field=models.CharField(choices=django_spire.celery.models._celery_state_choices, default='PENDING', max_length=32),
        ),
    ]
