# Generated by Django 6.0.6 on 2026-09-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_celery', '0004_alter_celerytask_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celerytask',
            name='task_id',
            field=models.UUIDField(editable=False, verbose_name='Celery Task ID'),
        ),
    ]
