from __future__ import annotations

from typing import Any, Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from datetime import datetime


class Storage(Protocol):
    def create_many(self, records: list[dict[str, Any]], hashes: dict[str, str]) -> None: ...
    def deactivate_many(self, keys: set[str]) -> None: ...
    def get_active_keys(self) -> set[str]: ...
    def get_hashes(self, keys: set[str]) -> dict[str, str]: ...
    def get_many(self, keys: set[str]) -> dict[str, dict[str, Any]]: ...
    def update_many(self, records: list[dict[str, Any]], hashes: dict[str, str]) -> None: ...


class BidirectionalStorage(Protocol):
    def create_many(self, records: list[dict[str, Any]], hashes: dict[str, str]) -> None: ...
    def deactivate_many(self, keys: set[str]) -> None: ...
    def get_active_keys(self) -> set[str]: ...
    def get_baseline_hashes(self) -> dict[str, str]: ...
    def get_hashes(self, keys: set[str]) -> dict[str, str]: ...
    def get_many(self, keys: set[str]) -> dict[str, dict[str, Any]]: ...
    def get_timestamps(self, keys: set[str]) -> dict[str, datetime]: ...
    def save_baseline_hashes(self, hashes: dict[str, str]) -> None: ...
    def update_many(self, records: list[dict[str, Any]], hashes: dict[str, str]) -> None: ...
