# Generated by Django 6.0.8 on 2026-08-09 23:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_spire_metric_domain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('indicator', 'Indicator'), ('line', 'Line'), ('bar', 'Bar'), ('area', 'Area'), ('pie', 'Pie'), ('gauge', 'Gauge')], default='indicator', max_length=20)),
                ('statistic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visuals', related_query_name='visual', to='django_spire_metric_domain.statistic')),
            ],
            options={
                'verbose_name': 'Visual',
                'verbose_name_plural': 'Visuals',
                'db_table': 'django_spire_metric_visual',
            },
        ),
        migrations.CreateModel(
            name='AreaChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Area Chart Visual',
                'verbose_name_plural': 'Area Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='BarChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Bar Chart Visual',
                'verbose_name_plural': 'Bar Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='GaugeChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Gauge Chart Visual',
                'verbose_name_plural': 'Gauge Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='IndicatorVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Indicator Visual',
                'verbose_name_plural': 'Indicator Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='LineChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Line Chart Visual',
                'verbose_name_plural': 'Line Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='PieChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Pie Chart Visual',
                'verbose_name_plural': 'Pie Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_spire_metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='VisualCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('state', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal To'), ('between', 'At or Near Target')], default='gt', max_length=10)),
                ('target', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', related_query_name='condition', to='django_spire_metric_visual.visual')),
            ],
            options={
                'verbose_name': 'Visual Condition',
                'verbose_name_plural': 'Visual Conditions',
                'db_table': 'django_spire_metric_visual_condition',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('visual', 'order'), name='unique_visual_condition_order')],
            },
        ),
    ]
