# Generated by Django 6.0.8 on 2026-08-09 06:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metric_domain', '0005_alter_statistic_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('statistic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visuals', related_query_name='visual', to='metric_domain.statistic')),
            ],
            options={
                'verbose_name': 'Visual',
                'verbose_name_plural': 'Visuals',
                'db_table': 'metric_visual',
            },
        ),
        migrations.CreateModel(
            name='VisualCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('state', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red')], default='green', max_length=10)),
                ('operator', models.CharField(choices=[('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('eq', 'Equal To'), ('between', 'At or Near Target')], default='gt', max_length=10)),
                ('target', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('tolerance', models.DecimalField(decimal_places=4, default=0, max_digits=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', related_query_name='condition', to='metric_visual.visual')),
            ],
            options={
                'verbose_name': 'Visual Condition',
                'verbose_name_plural': 'Visual Conditions',
                'db_table': 'metric_visual_condition',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('visual', 'order'), name='unique_visual_condition_order')],
            },
        ),
    ]
