# Generated by Django 6.0.8 on 2026-08-30 01:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('reference', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', related_query_name='reference', to='django_spire_metric_visual.visual')),
            ],
            options={
                'verbose_name': 'Visual Reference',
                'verbose_name_plural': 'Visual References',
                'db_table': 'django_spire_metric_visual_reference',
                'ordering': ('order',),
                'constraints': [models.UniqueConstraint(fields=('visual', 'order'), name='unique_visual_reference_order')],
            },
        ),
    ]
