# Generated by Django 6.0.8 on 2026-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metric_visual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Area Chart Visual',
                'verbose_name_plural': 'Area Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='BarChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Bar Chart Visual',
                'verbose_name_plural': 'Bar Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='GaugeChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Gauge Chart Visual',
                'verbose_name_plural': 'Gauge Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='IndicatorVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Indicator Visual',
                'verbose_name_plural': 'Indicator Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='LineChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Line Chart Visual',
                'verbose_name_plural': 'Line Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.CreateModel(
            name='PieChartVisual',
            fields=[
            ],
            options={
                'verbose_name': 'Pie Chart Visual',
                'verbose_name_plural': 'Pie Chart Visuals',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('metric_visual.visual',),
        ),
        migrations.AddField(
            model_name='visual',
            name='kind',
            field=models.CharField(choices=[('indicator', 'Indicator'), ('line', 'Line'), ('bar', 'Bar'), ('area', 'Area'), ('pie', 'Pie'), ('gauge', 'Gauge')], default='indicator', max_length=20),
        ),
    ]
