# Generated by Django 6.0.8 on 2026-08-30 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0003_auto_20260829_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visual',
            name='reference',
        ),
    ]
