# Generated by Django 6.0.8 on 2026-08-30 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0004_remove_visual_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualcondition',
            name='state',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow'), ('grey', 'Grey'), ('red', 'Red')], default='green', max_length=10),
        ),
    ]
