# Generated by Django 6.0.8 on 2026-08-30 21:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0005_alter_visualcondition_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_live_updated', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('visual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regions', related_query_name='region', to='django_spire_metric_visual.visual')),
            ],
            options={
                'verbose_name': 'Visual Region',
                'verbose_name_plural': 'Visual Regions',
                'db_table': 'django_spire_metric_visual_region',
                'ordering': ('key',),
            },
        ),
    ]
