# Generated by Django 6.0.6 on 2026-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('django_spire_metric_visual', '0007_remove_visual_date')]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='display_unit_count',
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name='Display units'
            ),
        )
    ]
