# Generated by Django 6.0.6 on 2026-10-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0008_visual_display_unit_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualcondition',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='visualcondition',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='visualreference',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='visualreference',
            name='is_deleted',
        ),
    ]
