# Generated by Django 5.1.8 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSequenceCounter',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_spire_sync_sequence_counter',
            },
        ),
        migrations.RenameField(
            model_name='synccheckpoint',
            old_name='timestamp',
            new_name='local_sequence_pushed',
        ),
        migrations.RenameField(
            model_name='synccheckpoint',
            old_name='node_id',
            new_name='peer_node_id',
        ),
        migrations.AddField(
            model_name='synccheckpoint',
            name='peer_sequence',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='synctombstone',
            name='origin_node',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='synctombstone',
            name='sequence',
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='synctombstone',
            index=models.Index(fields=['model_label', 'sequence'], name='sync_tombstone_model_seq_idx'),
        ),
    ]
