# Generated by Django 6.0.8 on 2026-08-31 17:54

from django.db import migrations, models


def dedupe_slide_section_cells(apps, schema_editor):
    SlideSection = apps.get_model(
        'django_spire_metric_visual_presentation', 'SlideSection'
    )

    occupied: set[tuple[int, int, int]] = set()
    sections = SlideSection.objects.order_by('slide_id', 'row', 'col', 'pk')

    for section in sections.iterator(chunk_size=500):
        cell = (section.slide_id, section.row, section.col)

        if cell in occupied:
            new_col = section.col
            while (section.slide_id, section.row, new_col) in occupied:
                new_col += 1

            occupied.add((section.slide_id, section.row, new_col))
            SlideSection.objects.filter(pk=section.pk).update(col=new_col)
        else:
            occupied.add(cell)


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual', '0006_visualregion'),
        ('django_spire_metric_visual_presentation', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_slide_section_cells, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='slidesection',
            constraint=models.UniqueConstraint(
                fields=('slide', 'row', 'col'), name='unique_slide_section_cell'
            ),
        ),
    ]
