# Generated by Django 6.0.6 on 2026-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual_presentation', '0002_slidesection_unique_slide_section_cell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='slidesection',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='slidesection',
            name='is_deleted',
        ),
    ]
