# Generated by Django 6.0.8 on 2026-08-10 16:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_spire_auth_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('code_hash', models.CharField(blank=True, default='', editable=False, max_length=128)),
                ('code_purpose', models.CharField(blank=True, choices=[('enro', 'Enrollment'), ('sess', 'Session')], default='', editable=False, max_length=4)),
                ('code_expiration_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('code_attempt_count', models.IntegerField(default=0, editable=False)),
                ('session_started_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('session_last_activity_datetime', models.DateTimeField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_smss', related_query_name='auth_sms', to='django_spire_auth_user.authuser')),
            ],
            options={
                'verbose_name': 'Auth SMS',
                'verbose_name_plural': 'Auth SMSs',
                'db_table': 'django_spire_auth_sms',
                'ordering': ('phone_number',),
            },
        ),
    ]
