# Generated by Django 5.2 on 2025-04-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='app_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
