# Generated by Django 5.2 on 2025-04-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0002_aiinteraction_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='exception',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='raised_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='stack_trace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
