# Generated by Django 5.2 on 2025-04-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0003_aiinteraction_exception_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinteraction',
            name='raised_exception',
        ),
        migrations.AddField(
            model_name='aiinteraction',
            name='was_successful',
            field=models.BooleanField(default=True),
        ),
    ]
