# Generated by Django 5.2 on 2025-04-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0004_remove_aiinteraction_raised_exception_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='module_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
