# Generated by Django 5.2 on 2025-04-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0005_aiinteraction_module_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinteraction',
            name='app_name',
        ),
    ]
