# Generated by Django 5.2 on 2025-04-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spire_ai', '0006_remove_aiinteraction_app_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinteraction',
            name='callable_name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
