# Generated by Django 5.2.1 on 2025-06-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_help_desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpdeskticket',
            options={'permissions': [('can_access_all_helpdeskticket', 'Can view, change, and delete all help desk tickets')], 'verbose_name': 'Help Desk Ticket', 'verbose_name_plural': 'Help Desk Tickets'},
        ),
    ]
