# Generated by Django 6.0.8 on 2026-08-09 23:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_spire_metric_visual_presentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Signage',
                'verbose_name_plural': 'Signages',
                'db_table': 'django_spire_metric_visual_signage',
            },
        ),
        migrations.CreateModel(
            name='SignagePresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_links', related_query_name='presentation_link', to='django_spire_metric_visual_presentation.presentation')),
                ('signage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signage_presentations', related_query_name='signage_presentation', to='django_spire_metric_visual_signage.signage')),
            ],
            options={
                'verbose_name': 'Signage Presentation',
                'verbose_name_plural': 'Signage Presentations',
                'db_table': 'django_spire_metric_visual_signage_presentation',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='signage',
            name='presentations',
            field=models.ManyToManyField(blank=True, related_name='signages', related_query_name='signage', through='django_spire_metric_visual_signage.SignagePresentation', through_fields=('signage', 'presentation'), to='django_spire_metric_visual_presentation.presentation'),
        ),
        migrations.AddConstraint(
            model_name='signagepresentation',
            constraint=models.UniqueConstraint(fields=('signage', 'order'), name='unique_signage_presentation_order'),
        ),
    ]
