# Generated by Django 6.0.8 on 2026-08-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual_signage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signage',
            name='slide_display_seconds',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
