# Generated by Django 6.0.8 on 2026-08-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual_signage', '0002_signage_slide_display_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='signage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
