# Generated by Django 6.0.6 on 2026-10-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spire_metric_visual_signage', '0003_signage_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signagepresentation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='signagepresentation',
            name='is_deleted',
        ),
    ]
