# Generated by Django 5.2.13 on 2026-05-04 05:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after_keys', models.JSONField(blank=True, default=dict)),
                ('node_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_spire_sync_checkpoint',
            },
        ),
        migrations.CreateModel(
            name='SyncNodeLock',
            fields=[
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_spire_sync_node_lock',
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('phase', models.CharField(default='collecting', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('records_pushed', models.PositiveIntegerField(default=0)),
                ('records_applied', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_deleted', models.PositiveIntegerField(default=0)),
                ('conflicts', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'django_spire_sync_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['node_id', 'status'], name='sync_session_node_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=255)),
                ('record_key', models.CharField(max_length=255)),
                ('timestamp', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_spire_sync_tombstone',
                'indexes': [models.Index(fields=['model_label', 'timestamp'], name='sync_tombstone_model_ts_idx')],
                'unique_together': {('model_label', 'record_key')},
            },
        ),
    ]
