# Generated by Django 5.2.13 on 2026-04-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncNodeLock',
            fields=[
                ('node_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
