# Generated by Django 5.1.8 on 2026-05-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_syncsequencecounter_and_more'),
    ]

    operations = [
        migrations.DeleteModel(name='SyncNodeLock'),
        migrations.CreateModel(
            name='SyncNodeLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('peer_node_id', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'django_spire_sync_node_lock',
                'unique_together': {('node_id', 'peer_node_id')},
            },
        ),
        migrations.CreateModel(
            name='SyncDeferredBackfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_label', models.CharField(max_length=255)),
                ('record_key', models.CharField(max_length=255)),
                ('attname', models.CharField(max_length=255)),
                ('fk_value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'django_spire_sync_deferred_backfill',
            },
        ),
        migrations.AddField(
            model_name='syncsession',
            name='peer_node_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='syncsession',
            index=models.Index(fields=['node_id', 'peer_node_id', 'status'], name='sync_session_pair_status_idx'),
        ),
        migrations.AddIndex(
            model_name='syncdeferredbackfill',
            index=models.Index(fields=['model_label'], name='sync_deferred_bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='syncdeferredbackfill',
            unique_together={('model_label', 'record_key', 'attname')},
        ),
    ]
