# Generated by Django 5.1.3 on 2024-11-08 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cookbook_recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'Cookbook',
                'verbose_name_plural': 'Cookbooks',
                'db_table': 'cookbook',
                'permissions': [('can_approve_cookbook', 'Can Approve Cookbook')],
            },
        ),
        migrations.CreateModel(
            name='CookbookRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', related_query_name='cookbook_recipe', to='example_cookbook.cookbook')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookbook_recipes', related_query_name='cookbook_recipe', to='cookbook_recipe.recipe')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
                'db_table': 'cookbook_recipe_m2m',
            },
        ),
    ]
