# Generated by Django 6.0.6 on 2026-07-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_rename_testrestuser_pirate_alter_pirate_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pirate',
            table='test_project_rest_pirate',
        ),
    ]
