# Generated by Django 6.0.8 on 2026-08-31 19:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Showcase Category',
                'verbose_name_plural': 'Showcase Categories',
                'db_table': 'test_project_showcase_category',
            },
        ),
        migrations.CreateModel(
            name='ShowcaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Showcase Tag',
                'verbose_name_plural': 'Showcase Tags',
                'db_table': 'test_project_showcase_tag',
            },
        ),
        migrations.CreateModel(
            name='WidgetShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.localtime, editable=False)),
                ('boolean_field', models.BooleanField(default=False)),
                ('char_field', models.CharField(blank=True, default='', max_length=255)),
                ('color_field', models.CharField(blank=True, default='#0d6efd', max_length=7)),
                ('email_field', models.EmailField(blank=True, default='', max_length=254)),
                ('password_field', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code_field', models.CharField(blank=True, default='', max_length=20)),
                ('search_field', models.CharField(blank=True, default='', max_length=255)),
                ('slug_field', models.SlugField(blank=True, default='')),
                ('telephone_field', models.CharField(blank=True, default='', max_length=20)),
                ('url_field', models.URLField(blank=True, default='')),
                ('uuid_field', models.UUIDField(default=uuid.uuid4)),
                ('select_choice', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4)),
                ('radio_choice', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='med', max_length=4)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('datetime_field', models.DateTimeField(blank=True, null=True)),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('currency_field', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('decimal_field', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('float_field', models.FloatField(blank=True, null=True)),
                ('hidden_field', models.CharField(blank=True, default='', max_length=64)),
                ('big_integer_field', models.BigIntegerField(blank=True, null=True)),
                ('integer_field', models.IntegerField(blank=True, null=True)),
                ('positive_integer_field', models.PositiveIntegerField(blank=True, null=True)),
                ('small_integer_field', models.SmallIntegerField(blank=True, null=True)),
                ('text_field', models.TextField(blank=True, default='')),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_showcases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcases', to='test_project_showcase.showcasecategory')),
                ('checkbox_tags', models.ManyToManyField(blank=True, related_name='checkbox_showcases', to='test_project_showcase.showcasetag')),
                ('search_tags', models.ManyToManyField(blank=True, related_name='search_showcases', to='test_project_showcase.showcasetag')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_showcases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget Showcase',
                'verbose_name_plural': 'Widget Showcases',
                'db_table': 'test_project_showcase_widget_showcase',
            },
        ),
    ]
