# Generated by Django 6.0.8 on 2026-09-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project_showcase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetshowcase',
            name='primary_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_showcases', to='test_project_showcase.showcasecategory'),
        ),
    ]
