# Generated by Django 6.0.8 on 2026-09-18 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_project_showcase', '0002_widgetshowcase_primary_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgetshowcase',
            name='formatted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatted_showcases', to='test_project_showcase.showcasecategory'),
        ),
    ]
