name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: stratusadv/github-actions/linting@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: linting
    timeout-minutes: 15
    env:
      OLLAMA_1_HOST: ${{ secrets.OLLAMA_1_HOST }}
      OLLAMA_2_HOST: ${{ secrets.OLLAMA_2_HOST }}
      OLLAMA_PORT: ${{ secrets.OLLAMA_PORT }}
      OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
      OPENAI_HOST: ${{ secrets.OPENAI_HOST }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      DANDY_SETTINGS_MODULE: ${{ secrets.DANDY_SETTINGS_MODULE }}
    steps:
      - uses: actions/checkout@v5
      - uses: stratusadv/github-actions/tests@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          settings-module: test_project.sqlite_settings
          sync-extras: development documentation

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: stratusadv/github-actions/security@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          sync-extras: ''
